### ISSUE TITLE
How to use the LibPostalNet

### ISSUE THREAD

**Issue by gdonaire** [mapo80/LibPostalNet#1]
Hello,

I download the solution and compile it.
But when I see the results of the libPostalConsole, they appear in non-comprensible language.

![image](https://user-images.githubusercontent.com/12764023/32490503-ab2d9f90-c3b3-11e7-8728-5070549b6b37.png)

Please, could you help me to fix this issue?

Thanks a lot,

**Comment by mapo80** [comment]
Hi, sorry for delay.

I think problem is here:

`Marshal.PtrToStringAuto`

Try to use: PtrToStringAnsi

Let me know.

**Comment by gdonaire** [comment]
Hi,

Yes, it works.
I change all the references in the libpostalparcial.cs file to Marshal.PtrToStringAnsi and rebuild solution.
And there is no errors.

Thanks a lot for your support.
Best Regards,

**Comment by mapo80** [comment]
Hi, I've update sourcecode and commit.

**Comment by zhanglo** [comment]
I download the project and try to run it in visual studio!  kept getting response is null error!  I am new to ,net app!
wonder what I missing here?
